services:
  # Django Backend Service
  - type: web
    name: chelal-hms-backend
    runtime: python
    rootDir: chelalBackend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: Backend.settings
      - key: DATABASE_URL
        fromDatabase:
          name: chelal-hms-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: chelal-hms-redis
          property: connectionString

  # PostgreSQL Database
  - type: pserv
    name: chelal-hms-db

  # Redis for caching and Celery
  - type: redis
    name: chelal-hms-redis

# Optional: Background worker for Celery (if needed)
# - type: worker
#   name: chelal-hms-worker
#   runtime: python3
#   buildCommand: pip install -r requirements.txt
#   startCommand: celery -A Backend worker --loglevel=info
#   envVars:
#     - key: DATABASE_URL
#       fromDatabase:
#         name: chelal-hms-db
#         property: connectionString
#     - key: REDIS_URL
#       fromService:
#         type: redis
#         name: chelal-hms-redis
#         property: connectionString